// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmoylflihtjjmuxbborz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtb3lsZmxpaHRqam11eGJib3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDIxODgsImV4cCI6MjA3MTg3ODE4OH0.YFeFvMxNwgAIGmx41_-BQhUha4yBTU06X3OPDsWTyV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});